### ISSUE TITLE
The dir attribute is already defined in the HTML spec

### ISSUE THREAD

**Issue by aaronpowell** [InternetExplorer/directory-upload#1]
In the proposal it states that you add a `dir` attribute to input (https://github.com/InternetExplorer/directory-upload/blob/gh-pages/proposal.html#L65) but the `dir` attribute is already defined in the HTML spec as part of global attributes and is on the input (http://www.w3.org/html/wg/drafts/html/CR/dom.html#the-dir-attribute).

Won't this cause conflict?

**Comment by aliams** [comment]
I agree this will cause conflict. We should definitely rename it to something else. We were contemplating what it should be called in light of also wanting to reserve `directory` for retrieving the virtual root directory. One option might be to change `directory` to another name (e.g. `rootDirectory`) and rename `dir` to `directory`.
