### ISSUE TITLE
Specify what HTMLInputElement::getFilesAndDirectories returns when the input type is not 'file'

### ISSUE THREAD

**Issue by jwatt** [InternetExplorer/directory-upload#13]
Right now the text says about HTMLInputElement::getFilesAndDirectories 'If the input type is not "file", nothing occurs.' What does that mean? Does that mean that it doesn't return anything (in which case the text should say it returns 'undefined' or 'null')? Or that a Promise is returned but doesn't resolve? I'd suggest that it should probably throw.

**Comment by inexorabletash** [comment]
For those not tracking the spec, the text changed in 7c0849056335313511874b7970d004df3ca36796 from "nothing occurs" to "returns null"

Was this resolved, or does there still need to be a decision about returning null vs. undefined vs. throw ?

**Comment by jwatt** [comment]
Ah yes, I should have closed this. Thanks!
