### ISSUE TITLE
The spec should define integration with FormData

### ISSUE THREAD

**Issue by jwatt** [InternetExplorer/directory-upload#14]
The spec should define how Directory objects interact with [FormData](https://xhr.spec.whatwg.org/#interface-formdata). Things like what happens when a Directory object is passed to the append() method. Note also that currently the text over there says about the filename field "its filename is the value of entry's value's name attribute", which ignores the 'path' data that the Directory Upload text currently says should be included in the filename field.

**Comment by jwatt** [comment]
On further reflection I don't think adding Directory objects directly to FormData objects should be supported. Directory objects have an unknown number of files under them, and blindly adding all files makes it likely that limits imposed on the number of files in a submission will be exceeded. (Browsers impose limits, as do servers - see for example Apache's max_file_uploads configuration option.) It seems better to force script to walk a Directory tree and FormData.append() files one at a time so that content is encourage to upload controlled numbers of files in batches.

**Comment by arunranga** [comment]
@jwatt: given your previous comment, I'm closing this.
