### ISSUE TITLE
Bikeshed: getFilesAndDirectories()

### ISSUE THREAD

**Issue by marcoscaceres** [InternetExplorer/directory-upload#25]
Sure, it's super clear... but it's so long. Maybe, `.listContent()`?

**Comment by arunranga** [comment]
Meh. Cc @jwatt . I'm terrible at bikeshedding and will simply do it if @jwatt agrees :)

**Comment by aliams** [comment]
We originally had something like `.getContents()`, but we figured it was not as clear as `.getFilesAndDirectories()` when we look at `HTMLInputElement` and `DataTransfer`. The goal was to have a homogeneous API across the different interfaces so it would be clear what you were getting back under any of those contexts. I would be open to naming it something else, but I feel like it should be clear what it does when it's called from `HTMLInputElement` or `DataTransfer`.

**Comment by marcoscaceres** [comment]
Ok, thanks for the background and good to hear that it was already bikesheded. Can certainly live with it :)
