### ISSUE TITLE
input.files shouldn't be null if directory attribute is used (or at least not if webkitdirectory attribute is also set)

### ISSUE THREAD

**Issue by smaug----** [InternetExplorer/directory-upload#29]
webkitdirectory attribute works in a bit different way and doesn't set .files to null.
The current https://wicg.github.io/directory-upload/proposal.html says about 'directory' that
"If this attribute is set, input.files MUST return null."
and since many examples in the web have _both_ directory and webkitdirectory attributes set, I don't think we can start returning null, at least if webkitdirectory is set.

**Comment by smaug----** [comment]
@jwatt

**Comment by smaug----** [comment]
Thinking this some more, I think we need to do it so that if webkitdirectory is set, then .files isn't null if user has selected some directory, but contains list of files in that directory (and subdirectories). Then, if one wants to use the new Promise based API, one must not set webkitdirectory but only directory. In that case .files would be null and the Promise returning methods would need to be used to access files and directories.

**Comment by smaug----** [comment]
or actually, one could always use the Promise based API, but if webkitdirectory is set, then .files must be populated synchronously.

**Comment by jwatt** [comment]
Not setting .files to null makes the Promised based API pointless. The 'input' event then cannot be sent until .files is fully populated and all I/O is finished.

**Comment by jwatt** [comment]
Devs are probably going to continue to put both 'directory' and 'webkitdirectory' on 'input' for backwards compatibility with old versions of Chrome/Opera. That would basically mean the Promise based API is dead in the water.

**Comment by smaug----** [comment]
Well, we can't change the current behavior where
<input type=file directory webkitdirectory> currently leads to populating .files synchronously on some browsers. Making that to lead null .files would be backwards incompatible.

**Comment by jwatt** [comment]
Maybe we should rename the 'directory' attribute to something else. 'dirpicker' perhaps.

**Comment by smaug----** [comment]
that might work indeed.

**Comment by jwatt** [comment]
Or since 'directory' implies 'multiple' anyway, maybe call it 'directories'.

**Comment by aliams** [comment]
This is a very interesting observation. Are there examples of sites that are using `directory` and `webkitdirectory` in conjunction to future-proof their implementation?

**Comment by smaug----** [comment]
Look at pretty much any example in the web using webkitdirectory. I saw people using even mozdirectory as a "forwards compatible" approach: `<input type=file directory webkitdirectory mozdirectory>`.

**Comment by aliams** [comment]
As unfortunate as that is, I agree that the best option is to change the name of the attribute. So far the options are:
- `dirpicker`
- `directories`
- `dir`
- `directorypicker`

Any others?

**Comment by smaug----** [comment]
dir has already meaning in HTML.

*picker sounds like a specific UI. The way to select files could be something else too, in theory. For example dnd. So, I guess 'directories' of those, assuming one can actually select several directories, not just one.

**Comment by aliams** [comment]
All good points. Regarding the `directories` choice, I would caution that in Windows and Linux it is not possible to select multiple directories, so it may cause confusion.

**Comment by smaug----** [comment]
one option is to change type. `<input type=directory>` ?

**Comment by aliams** [comment]
We pondered that and realized that we would break backwards compatibility. The nice thing about `<input type="file">` is that it allows older browsers that do not support the new directory functionality to still allow users to select files. If we introduced, for example, `<input type="directory">`, older browsers would not interpret that element correctly resulting in users not being able to even select file(s).

**Comment by smaug----** [comment]
Good point.
I assume 'folder' isn't too good. Doesn't sound quite platform neutral.
So, I'm not against directories.

**Comment by aliams** [comment]
I'm leaning towards `directories` as well. It may seem like a misnomer on Windows and Linux since only one directory can be chosen at a time, but I suppose the alternatives aren't any better.

**Comment by jwatt** [comment]
> Regarding the directories choice, I would caution that in Windows and Linux it is not possible to select multiple directories, so it may cause confusion.

But you can still drag and drop more than one directory onto the 'input', right? Either way, an 'input' in web content _could_ get more than one directory from a picker depending on the platform/browser the user is using, or if support for picking multiple directories is added to platforms/browsers in future. So it would be good to make devs think about and cater for that. But yes, worth a note in the spec I think.

**Comment by jwatt** [comment]
An alternative solution to this issue is to drop HTMLInputElement.getFilesAndDirectories(), put Directory objects in .files and solve the I/O issue using something like a 'willchange' event. ;)

**Comment by smaug----** [comment]
Directory objects in .files isn't backwards compatible.

**Comment by jwatt** [comment]
It is if they quack like a File (i.e. add lastModifiedDate etc., which makes some sense anyway).

**Comment by jwatt** [comment]
So there is a problem with calling the attribute `directories` and that is that in the IDL we'll have a boolean attribute "directories" and a FileList attribute "files". (See #31.) That is probably surprising for devs.

I propose we use `allowdirs` instead.

**Comment by jwatt** [comment]
Given that a directory picker falls back to being a file picker on things like mobile where there is no such thing as a directory picker, "allow" in the name seems like a good idea anyway. (The name "directory" always ran the risk that devs would think that the items that got returned would be Directory objects, which was never true. Even on desktop the immediately picked or dragged-onto-input list can contain a mixture of File and Directory objects.)

**Comment by aliams** [comment]
I like that. `allowdirs` it is!

**Comment by smaug----** [comment]
@bakulf

**Comment by bakulf** [comment]
I suggest 'allowdirectories' to be compatible with all the other places where we use the 'directory/ies' word and with the Directory interface.

**Comment by bakulf** [comment]
I also want to propose another change:
1. FileList should contain Directory objects (there is another bug for this issue), or alternatively
2. the 'directories' attribute that contains only the selected directories. This operation doesn't require I/O.

One of these 2 must be done, IMO, because otherwise there is not a sync and easy way to retrieve what the user chooses in case of directories.

**Comment by jwatt** [comment]
Regarding 'allowdirectories', I don't have a strong opinion. I personally like less typing, and I think most devs to do, but this isn't a big issue for me.

I am wondering whether we should use the word "enable" rather than "allow" though. My rational would be that some implementations will show just an "Upload Folder(s)" button, while others will show both an "Upload File(s)" and "Upload Folder(s)" button. The word "enable" seems more applicable to both scenarios, whereas "allow" seems a bit weird in the implementations where it doesn't just allow directories to _also_ be picked, but rather allows directories _only_ to be picked.

**Comment by jwatt** [comment]
Regarding FileList containing Directory objects, there is no FileList when directory picking is enabled.

Regarding having a 'directories' IDL attribute that contains only the selected directories, it may not involve I/O now, but it we were to add 'lastModifiedDate' and other things then it would.

**Comment by bakulf** [comment]
We have the same issue with File, don't we? At least we have the same pattern for Files and Directories.
Plus, it should be 'lastModified' and not 'lastModifiedDate' to be compatible with File API:
https://w3c.github.io/FileAPI/#dfn-FPdate
