### ISSUE TITLE
HTMLInputElement.directory should be a Directory attribute and not a boolean

### ISSUE THREAD

**Issue by bakulf** [InternetExplorer/directory-upload#31]
It seems confusing that HTMLInputElement.files return the array of selected files, but HTMLInputElement.directory just true/false. I think it would be nice to have it as:

```
readonly attribute Directory? directory;
```

In case the user selects 1 directory, this will be a Directory object.

**Comment by smaug----** [comment]
I don't think we can change this. Browsers supporting webkitdirectory, map that attribute to boolean.

**Comment by jwatt** [comment]
Indeed. The "directory" content attribute is a boolean content attribute, and as is normal for such attributes they are mapped into IDL as boolean attributes. The purpose of HTMLInputElement.directory is to tell script if this input element is a directory picker or not. It's purpose is not to give script access to the picked items.

Is your proposal that the IDL attribute should be true/false depending on whether the "directory" content attribute is set, except if there's actually directories picked? The complication is that there could be a mixture of File and Directory objects, not just a single Directory object. I think this is a bit too weird.
