### ISSUE TITLE
Consider to remove HTMLInputElement.getFilesAndDirectories andHTMLInputElement.getFiles

### ISSUE THREAD

**Issue by bakulf** [InternetExplorer/directory-upload#33]
Currently, without this spec, we have just one attribute to retrieve File objects: 'files'. This contains the list of files chosen by the user. It is synchronous with the 'change' event.
Personally I think we should follow the same approach with the Directory picker. Once the user chooses a directory, we populate .directories (or we add the Directory support in the FileList and in the 'files' attribute).
All the I/O needed can be done by the browser before dispatching the 'change' event. And I also like the JWatt's proposal of having willchange event (See issue #11).

If we do this, we can get rid of getFilesAndDirectories and getFiles from the HTMLInputElement completely. Directory object, of course, will still have getFilesAndDirectories and getFiles methods.

This will make the HTMLInputElement interface extremely simple and nice. And consistent: .files will be always a FileList. Here the interface:

```
partial interface HTMLInputElement {
             attribute boolean allowDirectory;
    readonly attribute DirList directories; // or just remove this and support Directory in 'files'
};
```

**Comment by aliams** [comment]
We considered this earlier on, but soon realized that the major pitfall with `HTMLInputElement.files` was that it fell victim to the synchronous nature of property retrieval. One of the main advantages and motivations for this spec was to go to a completely asynchronous model. This could enable better user experiences by allowing developers to be able to provide visual feedback to users about what is going on while the items are being processed. Both Mozilla and Microsoft verified that Firefox, Edge, and Chrome can take time to process many files/folders which would result in holding up execution of the JavaScript until the `FileList` is generated and passed through to `HTMLInputElement.files`. By introducing `Promises` (or `AsyncIterators` in the future), we can move to a model that works better for this sort of processing.

**Comment by bakulf** [comment]
We can have a similar behavior introducing 'will-change' event. And we can dispatch the 'changed' event only when the `FileList` is fully generated and passed through to `HTMLInputElement.files`.

**Comment by aliams** [comment]
If I'm not mistaken, I believe doing that may break backwards compatibility.

**Comment by smaug----** [comment]
yeah, we can't change the existing .files handling, like it can't really have Directory objects since
at least in case <input> has webkitdirectory or directory attribute.
So what should happen in case of
<input type=file webkitdirectory directories> ?

I think I'd prefer to have the upload API proposal stuff too (even if browsers were forced to support webkitdirectory too)

**Comment by smaug----** [comment]
And I prefer the consistency in input element and Directory having the same way to access files and subdirectories.
(it might make sense to put the common methods to a separate [NoInterfaceObject] interface and make input element and Directory to implement it)

**Comment by jwatt** [comment]
> If I'm not mistaken, I believe doing that may break backwards compatibility.

How so?

**Comment by jwatt** [comment]
> yeah, we can't change the existing .files handling, like it can't really have Directory objects since at least in case has webkitdirectory or directory attribute. So what should happen in case of?

I don't follow. If we added a 'allowdirectories' attribute that would opt-in to different behavior to webkitdirectory.

**Comment by smaug----** [comment]
I would expect allowdirectories to not affect to the behavior of webkitdirectory API.
They are totally different APIs, and could stay so. That way whatever random libraries web sites use would work without updates, and once everything is updated to use the new API, webkitdirectory could be dropped, and more asynchronous behavior achieved.
