### ISSUE TITLE
readEntries needs to be called until no items are left

### ISSUE THREAD

**Issue by bookman25** [InternetExplorer/directory-upload#37]
Currently readEntries is only returning 100 items in the directory.  If the directory has more than 100 direct children then we're only getting a partial resultset.  According to the API's `readEntries` needs to be called multiple times until there are no items left in the array.

https://developer.mozilla.org/en-US/docs/Web/API/DirectoryReader

**Comment by aliams** [comment]
Fixed!

**Comment by bookman25** [comment]
Thanks, that was very prompt :)
