### ISSUE TITLE
Repository redirect or Organization redirect to MicrosoftEdge

### ISSUE THREAD

**Issue by ghost** [InternetExplorer/directory-upload#4]
As noted here: https://github.com/blog/1508-repository-redirects-are-here, you can redirect `InternetExplorer` repositories and/or the whole gh-organization to `MicrosoftEdge`.

Case in hand is io.js. It used to be https://github.com/iojs/io.js/io.js, ever since the inception of nodejs organization navigating to that link automatically redirects to https://github.com/nodejs/io.js.

This will prevent duplicating the repositories and adding the redirect link in README.md manually. :)

**Comment by aliams** [comment]
We had it set up that way originally, unfortunately, none of the github.io links redirected correctly. Apparently that isn't supported yet, so we had to do it this way :(

**Comment by ghost** [comment]
Thanks for quick response. If you leave their support team a quick message describing this anomaly here: https://github.com/contact, you will be amazed to find out how receptive they are in fixing this kind of issues :smile:

**Comment by aliams** [comment]
Thank you for the tip! I'll give that a try and let you know if they can do anything to help.

**Comment by aliams** [comment]
Closing as this repository now lives in the `WICG` organization and is no longer associated to the `MicrosoftEdge` and `InternetExplorer` organizations on GitHub.

**Comment by ghost** [comment]
Thanks @aliams! 
Would probably a good idea to redirect https://github.com/InternetExplorer/directory-upload to https://github.com/WICG/directory-upload as well as https://github.com/MicrosoftEdge/directory-upload is redirecting.

Alternatively, same affect can also be achieved by emptying source tree at https://github.com/InternetExplorer/directory-upload and leaving only Readme with note: "This repository has moved to https://github.com/WICG/directory-upload". E.g. https://github.com/joyent/libuv/

**Comment by aliams** [comment]
Both should be redirecting to the WICG repository now =)
