### ISSUE TITLE
path 'relative to its root directory'

### ISSUE THREAD

**Issue by silverwind** [InternetExplorer/directory-upload#6]
The current ['relative to its root directory'](https://github.com/MicrosoftEdge/directory-upload/blob/9d5805d9807a692acd0fbef4c1201208869516a1/proposal.html#L58) seems a bit unclear to me. The [FileSystem API](http://w3c.github.io/filesystem-api/#dfn-path-from-root) defines

1) **path from root** eg `/music/genres/jazz`
2) **relative path** eg `jazz`

I assume the first case is meant?

**Comment by aliams** [comment]
Thank you for your feedback @silverwind. This is now defined as "path from root."
