### ISSUE TITLE
getFilesAndDirectories should match that in FileSystem API

### ISSUE THREAD

**Issue by arunranga** [InternetExplorer/directory-upload#7]
Currently, getFilesAndDirectories() method definition is different than the one in FileSystem API. We should make them resemble each other. In particular, we should define what a snapshot is, e.g. if it is different from http://www.w3.org/TR/FileAPI/#snapshot-state

**Comment by aliams** [comment]
What's the best way to do this since it has already been fleshed out in the FileSystem API? Should I reference the FileSystem API spec and point out the relevant bits in the directory upload spec? Or would it make more sense to copy over the details into the directory upload spec?

**Comment by arunranga** [comment]
It probably makes sense to reference the spec. as far as Directory goes, since that way we won't propagate errors by keeping them out of sync.

But the method in question is on two separate interfaces: HTMLInputElement also. 

So I filed https://www.w3.org/Bugs/Public/show_bug.cgi?id=29154

**Comment by arunranga** [comment]
Also, whatwg issue: https://github.com/whatwg/html/issues/217

**Comment by arunranga** [comment]
Closing this; the dependency on FileSystem API has been lifted.
