### ISSUE TITLE
Is "sequence<File or Directory>" syntax correct/legal?

### ISSUE THREAD

**Issue by AFBarstow** [InternetExplorer/directory-upload#9]
The use cases imply the APIs needs to support a sequence of Files and/or Directory objects and the Web IDL syntax used is:

   Promise<sequence<(File or Directory)>>

My take on [Web IDL sequences](http://heycam.github.io/webidl/#idl-sequence) is that they support a single type. As such, the above doesn't seem correct; perhaps a union or some type of abstract type (for File plus Directory objects) is needed?

**Comment by aliams** [comment]
From the [Type definition](http://heycam.github.io/webidl/#prod-Type), it appears that the syntax is correct:

`[73] Type → SingleType | UnionType Null`

Specifically, a Type can be a [UnionType](http://heycam.github.io/webidl/#prod-UnionType):

`[75] UnionType → "(" UnionMemberType "or" UnionMemberType UnionMemberTypes ")"`

**Comment by jwatt** [comment]
It is correct. This issue can be closed.
